In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
train_df = pd.read_csv('vehicle_train.csv')
test_df = pd.read_csv('vehicle_test.csv')
train_labes = pd.read_csv('vehicle_training_labels.csv')

In [3]:
train_labes.value_counts()

Class
0        189
1        180
3        177
2        173
dtype: int64

In [4]:
train_df = train_df.drop(columns='ID')
test_df = test_df.drop(columns='ID')

In [5]:
train_df = train_df.dropna()
test_df = test_df.dropna()

In [6]:
train_df.info(), test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 719 entries, 0 to 718
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Comp          719 non-null    int64
 1   Circ          719 non-null    int64
 2   D.Circ        719 non-null    int64
 3   Rad.Ra        719 non-null    int64
 4   Pr.Axis.Ra    719 non-null    int64
 5   Max.L.Ra      719 non-null    int64
 6   Scat.Ra       719 non-null    int64
 7   Elong         719 non-null    int64
 8   Pr.Axis.Rect  719 non-null    int64
 9   Max.L.Rect    719 non-null    int64
 10  Sc.Var.Maxis  719 non-null    int64
 11  Sc.Var.maxis  719 non-null    int64
 12  Ra.Gyr        719 non-null    int64
 13  Skew.Maxis    719 non-null    int64
 14  Skew.maxis    719 non-null    int64
 15  Kurt.maxis    719 non-null    int64
 16  Kurt.Maxis    719 non-null    int64
 17  Holl.Ra       719 non-null    int64
dtypes: int64(18)
memory usage: 106.7 KB
<class 'pandas.core.frame.DataFram

(None, None)

In [7]:
scaler = MinMaxScaler()

In [8]:
train_df

Comp  Circ  D.Circ  Rad.Ra  Pr.Axis.Ra  Max.L.Ra  Scat.Ra  Elong  \
0      88    39      70     166          66         7      148     44   
1      85    35      64     129          57         6      116     57   
2      91    41      84     141          57         9      149     45   
3     102    54      98     177          56        10      219     31   
4      87    39      74     152          58         6      151     44   
..    ...   ...     ...     ...         ...       ...      ...    ...   
714   111    58     105     183          51         6      265     26   
715    93    43      76     149          57         7      149     44   
716    90    42      63     144          59         7      131     50   
717   101    56     101     231          72        10      217     31   
718    99    38      74     184          66         6      164     39   

     Pr.Axis.Rect  Max.L.Rect  Sc.Var.Maxis  Sc.Var.maxis  Ra.Gyr  Skew.Maxis  \
0              19         134           167           332     143          69   
1              17         125           138           200     123          65   
2              19         143           170           330     158          72   
3              25         171           219           706     223          72   
4              19         136           174           337     140          70   
..            ...         ...           ...           ...     ...         ...   
714            29         174           285          1018     255          85   
715            19         143           172           335     176          69   
716            18         142           154           259     162          65   
717            24         171           232           698     216          72   
718            20         131           193           414     137          71   

     Skew.maxis  Kurt.maxis  Kurt.Maxis  Holl.Ra  
0             5          13         193      201  
1             1          23         196      203  
2             9          14         189      199  
3             5          17         186      196  
4             1          33         187      196  
..          ...         ...         ...      ...  
714           4           8         181      183  
715          14           0         189      194  
716          15           3         197      204  
717           2           6         187      197  
718           2          22         200      202  

[719 rows x 18 columns]

In [9]:
train_df[['Comp', 'Circ', 'D.Circ', 'Rad.Ra', 'Pr.Axis.Ra', 'Max.L.Ra', 'Scat.Ra',
        'Elong', 'Pr.Axis.Rect', 'Max.L.Rect', 'Sc.Var.Maxis', 'Sc.Var.maxis',
          'Ra.Gyr', 'Skew.Maxis', 'Skew.maxis', 'Kurt.maxis', 'Kurt.Maxis', 'Holl.Ra']] = scaler.fit_transform(train_df[['Comp', 'Circ', 'D.Circ', 'Rad.Ra', 'Pr.Axis.Ra', 
                                                                                                              'Max.L.Ra','Scat.Ra', 'Elong', 'Pr.Axis.Rect', 'Max.L.Rect', 'Sc.Var.Maxis',
                                                                                                              'Sc.Var.maxis','Ra.Gyr', 'Skew.Maxis', 'Skew.maxis', 'Kurt.maxis', 'Kurt.Maxis', 'Holl.Ra']])

test_df[['Comp', 'Circ', 'D.Circ', 'Rad.Ra', 'Pr.Axis.Ra', 'Max.L.Ra', 'Scat.Ra',
        'Elong', 'Pr.Axis.Rect', 'Max.L.Rect', 'Sc.Var.Maxis', 'Sc.Var.maxis',
          'Ra.Gyr', 'Skew.Maxis', 'Skew.maxis', 'Kurt.maxis', 'Kurt.Maxis', 'Holl.Ra']] = scaler.fit_transform(test_df[['Comp', 'Circ', 'D.Circ', 'Rad.Ra', 'Pr.Axis.Ra', 
                                                                                                              'Max.L.Ra','Scat.Ra', 'Elong', 'Pr.Axis.Rect', 'Max.L.Rect', 'Sc.Var.Maxis',
                                                                                                              'Sc.Var.maxis','Ra.Gyr', 'Skew.Maxis', 'Skew.maxis', 'Kurt.maxis', 'Kurt.Maxis', 'Holl.Ra']])

In [10]:
x = train_df
y = train_labes
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [11]:
SVM_model = SVC(C=50, gamma=50, kernel='linear')
SVM_model.fit(x_train, y_train)

C:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(C=50, gamma=50, kernel='linear')

In [12]:
SVM_model.score(x_test, y_test)
SVM_predictions = SVM_model.predict(x_test)

In [13]:
RF_model = RandomForestClassifier(n_estimators=50, criterion='gini')
RF_model.fit(x_train, y_train.values.ravel())
RF_predictions = RF_model.predict(x_test)

In [14]:
print('SVM')
print(metrics.confusion_matrix(y_test, SVM_predictions))
print(metrics.classification_report(y_test, SVM_predictions))
print(metrics.accuracy_score(y_test, SVM_predictions))
print('Random Forest\n')
print(metrics.confusion_matrix(y_test, RF_predictions))
print(metrics.classification_report(y_test, RF_predictions))
print(metrics.accuracy_score(y_test, RF_predictions))

SVM
[[34  1  0  0]
 [ 1 24 14  1]
 [ 0 10 23  1]
 [ 0  1  0 34]]
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        35
           1       0.67      0.60      0.63        40
           2       0.62      0.68      0.65        34
           3       0.94      0.97      0.96        35

    accuracy                           0.80       144
   macro avg       0.80      0.80      0.80       144
weighted avg       0.80      0.80      0.80       144

0.7986111111111112
Random Forest

[[34  0  0  1]
 [ 2 18 18  2]
 [ 3 12 16  3]
 [ 0  0  0 35]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92        35
           1       0.60      0.45      0.51        40
           2       0.47      0.47      0.47        34
           3       0.85      1.00      0.92        35

    accuracy                           0.72       144
   macro avg       0.70      0.72      0.71       144
weighted avg       0.70  